# fly.toml file generated for dailytweet on 2022-07-06T16:41:17+07:00

app = "dailytweet"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
